### ISSUE TITLE
Why Android App removed from Play store?

### ISSUE THREAD

**Issue by xianx** [artivisi/playsms-android#5]
Why Android App removed from Play store?

**Comment by xianx** [comment]
Any reply?

**Comment by antonraharja** [comment]
was taken down by google

**Comment by xianx** [comment]
1. for which reason?
2. Where can find the officials.

**Comment by antonraharja** [comment]
1. Not sure why, probably because of icon files or description
2. What official ? APK ? I put it somewhere I don't remember, maybe you can compile yourself

anton

**Comment by xianx** [comment]
Can't you re submit to play store?

**Comment by xianx** [comment]
Can't it be re-submit to play store?
